apiVersion: v1
kind: Namespace
metadata:
  name: operator
  labels:
    name: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3db-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: m3db-operator
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - create
  - get
  - update
  - delete
  - list
- apiGroups:
  - operator.m3db.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: m3db-operator
  namespace: operator  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: m3db-operator
subjects:
- kind: ServiceAccount
  name: m3db-operator
  namespace: operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3db-operator
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m3db-operator
  template:
    metadata:
      labels:
        name: m3db-operator
    spec:
      containers:
        - name: m3db-operator
          image: <registry>/<repo>/m3db-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - m3db-operator
          args:
          - "-log-level"
          - "debug"
          imagePullPolicy: Always
          env:
            - name: OPERATOR_NAME
              value: "m3db-operator"
      serviceAccount: m3db-operator
